name: GitHub Classroom Workflow

on: 
    push:
        branches:
            - main
            - auto-grader-test-**
    pull_request:
        branches:
          - main
    workflow_dispatch:

permissions:
    checks: write
    actions: read
    contents: read

jobs:
    run-auto-grade:
        name: Autograding
        runs-on: ubuntu-latest
        
        env:
          GH_TOKEN: ${{ github.token }}

        outputs:
          points_gained: ${{ steps.marks.outputs.points_gained }}
          total_points: ${{ steps.marks.outputs.total_points }}

        steps:
            - uses: actions/checkout@v3
            
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'

            - name: Install dependencies
              run: pip install flake8 black pytest

            - name: Format with Black
              run: |
                find . -name "*.py" -print0 | xargs -0 black --preview --line-length=100
              continue-on-error: true

            - name: Lint with Flake8
              run: |
                find . -name "*.py" -print0 | xargs -0 flake8 --max-line-length=100 --ignore=E402,F841,F401,E302,E305,E266,E203,W503
              continue-on-error: true

            - uses: education/autograding@v1
              name: Run the Grading Script

            - name: Extract Marks from logs
              id: marks
              run: |
                points_line=$(gh run view 6080510862 --log | grep Points)
                points_gained=$(echo $points_line | awk '{print $NF}' | cut -d'/' -f1)
                total_points=$(echo $points_line | awk '{print $NF}' | cut -d'/' -f2)

                echo "points_gained=$points_gained" >> "$GITHUB_OUTPUT"
                echo "total_points=$total_points" >> "$GITHUB_OUTPUT"

    post_marks:
        name: Post marks
        runs-on: ubuntu-latest

        needs: run-auto-grade

        steps:
          - env:
              points_gained: ${{needs.run-auto-grade.outputs.points_gained}}
              total_points: ${{needs.run-auto-grade.outputs.total_points}}
            run: echo "Marks $points_gained/$total_points"

