name: GitHub Classroom Workflow

on: 
    push:
        branches:
            - main
            - auto-grader-test-**
    pull_request:
        branches:
          - main
    workflow_dispatch:

permissions:
    checks: write
    actions: read
    contents: read

jobs:
    run-auto-grade:
        name: Autograding
        runs-on: ubuntu-latest
        timeout-minutes: 2

        steps:
            - uses: actions/checkout@v3
            
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'

            - name: Install dependencies
              run: pip install flake8 black pytest

            - name: Format with Black
              run: |
                black lab2.py --check --preview --line-length=120
              continue-on-error: true

            - name: Lint with Flake8
              run: |
                flake8 lab2.py --max-line-length=120 --ignore=E402,E302,E305,E266,E203,W503,E722,E712,E721,E713,E714,E731
              continue-on-error: true

            - uses: education/autograding@v1
              name: Run the Grading Script
              continue-on-error: true